lastchecked : "2018-08-23 12:02:39.444204"
auditors : 
    - name : "EBSSnapshotAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_access"
          - name : "check_internet_accessible"
          - name : "check_marketplace_access"
          - name : "check_thirdparty_access"
          - name : "check_unknown_access"
    - name : "SESAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_verified"
    - name : "CloudTrailAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_if_cloudtrail_in_all_regions"
          - name : "check_if_cloudtrail_is_enabled"
    - name : "ELBv2Auditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_deletion_protection"
          - name : "check_internet_facing"
          - name : "check_logging"
          - name : "check_ssl_policy"
    - name : "SecurityGroupAuditor"
      methods : 
          - name : "_check_cross_account"
          - name : "_check_for_override_score"
          - name : "_check_internet_accessible"
          - name : "check_friendly_cross_account_egress"
          - name : "check_friendly_cross_account_ingress"
          - name : "check_internet_accessible_egress"
          - name : "check_internet_accessible_inress"
          - name : "check_securitygroup_ec2_rfc1918"
          - name : "check_thirdparty_cross_account_egress"
          - name : "check_thirdparty_cross_account_ingress"
          - name : "check_unknown_cross_account_egress"
          - name : "check_unknown_cross_account_ingress"
    - name : "RDSSnapshotAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "OpenStackSecurityGroupAuditor"
      methods : 
          - name : "_check_cross_account"
          - name : "_check_for_override_score"
          - name : "_check_internet_accessible"
          - name : "check_friendly_cross_account_egress"
          - name : "check_friendly_cross_account_ingress"
          - name : "check_internet_accessible_egress"
          - name : "check_internet_accessible_inress"
          - name : "check_securitygroup_ec2_rfc1918"
          - name : "check_thirdparty_cross_account_egress"
          - name : "check_thirdparty_cross_account_ingress"
          - name : "check_unknown_cross_account_egress"
          - name : "check_unknown_cross_account_ingress"
    - name : "Route53Auditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_for_public_zone_with_private_records"
    - name : "GCEFirewallRuleAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_allowed"
          - name : "check_source_ranges"
          - name : "check_target_tags"
    - name : "GlacierVaultAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "RedshiftAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_running_in_vpc"
    - name : "KMSAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_for_kms_key_rotation"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "ManagedPolicyAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_iam_passrole"
          - name : "check_iam_star_privileges"
          - name : "check_mutable_sensitive_services"
          - name : "check_notaction"
          - name : "check_notresource"
          - name : "check_permissions"
          - name : "check_security_group_permissions"
          - name : "check_star_privileges"
          - name : "library_check_attached_managed_policies"
    - name : "GCSBucketAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_acl"
          - name : "check_cors"
          - name : "check_default_object_acl"
    - name : "RDSDBClusterAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_internet_accessible"
    - name : "IAMUserAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_access_key_last_used"
          - name : "check_access_key_rotation"
          - name : "check_active_access_keys"
          - name : "check_attached_managed_policies"
          - name : "check_iam_passrole"
          - name : "check_iam_star_privileges"
          - name : "check_inactive_access_keys"
          - name : "check_loginprofile_plus_akeys"
          - name : "check_mutable_sensitive_services"
          - name : "check_no_mfa"
          - name : "check_notaction"
          - name : "check_notresource"
          - name : "check_permissions"
          - name : "check_security_group_permissions"
          - name : "check_star_privileges"
          - name : "library_check_attached_managed_policies"
    - name : "GitHubRepoAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_for_admin_teams"
          - name : "check_for_deploy_keys"
          - name : "check_for_no_protected_branches"
          - name : "check_for_outside_collaborators"
          - name : "check_for_public_repo"
          - name : "check_if_forked_repo"
    - name : "SQSAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "IAMServiceAccountAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_serviceaccount"
    - name : "ElasticSearchServiceAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "RDSDBInstanceAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_internet_accessible"
    - name : "IAMGroupAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_attached_managed_policies"
          - name : "check_iam_passrole"
          - name : "check_iam_star_privileges"
          - name : "check_mutable_sensitive_services"
          - name : "check_notaction"
          - name : "check_notresource"
          - name : "check_permissions"
          - name : "check_security_group_permissions"
          - name : "check_star_privileges"
          - name : "library_check_attached_managed_policies"
    - name : "SNSAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_snstopicpolicy_empty"
          - name : "check_subscriptions_crossaccount"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "VPCAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_flow_logs_enabled"
    - name : "VPNAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_tunnels"
    - name : "IAMSSLAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_cert_size_lt_1024"
          - name : "check_cert_size_lt_2048"
          - name : "check_expired"
          - name : "check_future_expiration"
          - name : "check_issuer"
          - name : "check_signature_algorith_for_md5"
          - name : "check_signature_algorith_for_sha1"
          - name : "check_upcoming_expiration"
          - name : "check_upload_date_for_heartbleed"
    - name : "IAMRoleAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_attached_managed_policies"
          - name : "check_friendly_cross_account"
          - name : "check_iam_passrole"
          - name : "check_iam_star_privileges"
          - name : "check_internet_accessible"
          - name : "check_mutable_sensitive_services"
          - name : "check_notaction"
          - name : "check_notresource"
          - name : "check_permissions"
          - name : "check_root_cross_account"
          - name : "check_security_group_permissions"
          - name : "check_star_privileges"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
          - name : "library_check_attached_managed_policies"
    - name : "OpenStackObjectContainerAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_acls"
    - name : "ELBAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_internet_scheme"
          - name : "check_listener_reference_policy"
          - name : "check_logging"
    - name : "ACMAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_expired"
          - name : "check_future_expiration"
          - name : "check_upcoming_expiration"
    - name : "RDSSecurityGroupAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "_check_inclusion_in_network_whitelist"
          - name : "check_rds_ec2_rfc1918"
          - name : "check_securitygroup_10net"
          - name : "check_securitygroup_any"
          - name : "check_securitygroup_large_subnet"
          - name : "check_securitygroup_zero_subnet"
    - name : "S3Auditor"
      methods : 
          - name : "_check_acl"
          - name : "_check_for_override_score"
          - name : "check_acl_friendly_canonical"
          - name : "check_acl_friendly_legacy"
          - name : "check_acl_internet_accessible"
          - name : "check_acl_log_delivery"
          - name : "check_acl_thirdparty_canonical"
          - name : "check_acl_thirdparty_legacy"
          - name : "check_acl_unknown"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_policy_exists"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "EC2ImageAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
    - name : "GitHubTeamAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_for_public_team"
    - name : "GitHubOrgAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_for_non_twofa_members"
          - name : "check_for_public_repo"
    - name : "GCENetworkAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_networks"
    - name : "LambdaFunctionAuditor"
      methods : 
          - name : "_check_for_override_score"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
