lastchecked : "2018-08-23 12:02:39.444204"
auditors : 
    - name : "S3Auditor"
      methods : 
          - name : "_check_acl"
          - name : "_check_for_override_score"
          - name : "check_acl_friendly_canonical"
          - name : "check_acl_friendly_legacy"
          - name : "check_acl_internet_accessible"
          - name : "check_acl_log_delivery"
          - name : "check_acl_thirdparty_canonical"
          - name : "check_acl_thirdparty_legacy"
          - name : "check_acl_unknown"
          - name : "check_friendly_cross_account"
          - name : "check_internet_accessible"
          - name : "check_policy_exists"
          - name : "check_root_cross_account"
          - name : "check_thirdparty_cross_account"
          - name : "check_unknown_cross_account"
